### ISSUE TITLE
Case creation page redirect for Mac.

### ISSUE THREAD

**Issue by darkvaderfr** [OnyxSpartanII/JudgeFrog#15]
On mac, the next button on case creation page does not work.

**Comment by darkvaderfr** [comment]
This was only an issue on localhost MAC machines.

**Comment by OnyxSpartanII** [comment]
Didn't this get resolved on the test domain?

**Comment by darkvaderfr** [comment]
Yes it was never a problem that's why I closed the case/issue. Read my closing comments

Sincerely,

Brice Boula
Texas Christian University -  Class of 2015
College of Science and Engineering - Computer Information Technology
AddRan College of Liberal Arts - French

"If knowledge is a weapon, let's be armed"

**Comment by OnyxSpartanII** [comment]
Ahh, whoops, it didn't show that in the email notification I got. I thought this was a new issue for some reason.
