### ISSUE TITLE
Bugs and Potential Fixes

### ISSUE THREAD

**Issue by lwestrom** [OnyxSpartanII/JudgeFrog#16]
- Each defendant’s OCG section may be different but does not make sense. 
  ![screen shot 2015-03-27 at 3 40 34 pm](https://cloud.githubusercontent.com/assets/9438783/6877476/4a9e8474-d49f-11e4-80c9-ae00565f47aa.png)

---
- Restitution in modal had a dollar sign for money value but fines and bail amount do not. Maybe something we should add. 
  ![screen shot 2015-03-27 at 3 52 48 pm](https://cloud.githubusercontent.com/assets/9438783/6877465/3cdb3eea-d49f-11e4-8f91-4dd61582fbb8.png)
  ![screen shot 2015-03-27 at 3 44 12 pm](https://cloud.githubusercontent.com/assets/9438783/6877466/3cdb3b70-d49f-11e4-9432-eefc262b581d.png)
  ![screen shot 2015-03-27 at 3 44 29 pm](https://cloud.githubusercontent.com/assets/9438783/6877467/3cde14ee-d49f-11e4-9b75-43fb40bbf220.png)

---
- Every defendant’s statute (1916 to 1968) shows n/a but other statutes show 0. Not consistent.
  ![screen shot 2015-03-27 at 4 06 59 pm](https://cloud.githubusercontent.com/assets/9438783/6877455/3200168a-d49f-11e4-9496-6a60d5851d39.png)

**Comment by cgduncan7** [comment]
I'll get this fixed today.

**Comment by cgduncan7** [comment]
I'm not sure what you mean by every defendant's statute does this. This is clearly false if you looked at different defendants.

**Comment by lwestrom** [comment]
I'll look at this again

**Comment by cgduncan7** [comment]
Fixed!
