### ISSUE TITLE
Case Insertion Bugs

### ISSUE THREAD

**Issue by lwestrom** [OnyxSpartanII/JudgeFrog#20]
- Combo's don't display correct value when you go back to edit a case
- [x] Gender
- [x] Appointed By
- Defendant Insertion
- [x] error occurs when you enter a defendant
    ex: (An error occurred while adding defendant to case.)

**Comment by OnyxSpartanII** [comment]
The gender and appointed by are known, and I think have to do with how booleans interact with restoring default values to form inputs.

The error is because validation is still failing. I'm working through the validation errors now.

**Comment by OnyxSpartanII** [comment]
Appointed By, JudgeGen and DefGender should now all display properly. Validation errors seem to be resolved too.

**Comment by lwestrom** [comment]
- [x] <strike>Case deletion errors with a missing a controller now. (AdminController could not be found.) </strike>
- [x]  <strike>Adding a defendant : needs some sort of required field. If no fields are entered and user clicks submit. The case is removed.  </strike>
- [x]  <strike> Validation still does not accept date format when entering a defendant  </strike>
- [x] <strike> In review. If approve case button is clicked <b> without </b> a case selected a empty case is inserted into database. </strike>
- [x] <strike> Once case is submitted to Data table in database from the review page in admin panel, if the user searches for that specific case and clicks on it, the modal window will <b> NOT </b> appear. </strike> Update: bullet bellow
- [x] If charge date is not specified for defendant, case modal will not display.
- [x] Download CSV file: case data is off sync because of missing column names 
- [x] Need to change "defendant first required" to "defendant last required"
- [x] Charge date: required verification is not working 
- [x] termination date null value in modal 
- [x] caseNam & caseNum verification is not working
- [x] <strike>  Show all "cases pending" for all users </strike>  
- [x] If defendant's first name is not entered, the defendant will be added to the db but not into the defendant table of the case viewable by the user
- [x] Months sentenced does not work when case is submitted to review. Always displays "N/A"

**Comment by darkvaderfr** [comment]
1- Case deletion errors Fixed.
3 - Could you elaborate more on this? It does not accept the date format how?
5 - You probably did not fill out all the defendant's information. I just tried entering a case and it does show on the search page (i.e USA v Bachmann)

**Comment by lwestrom** [comment]
- [ ] Redirect error when trying to access admin panel now

**Comment by lwestrom** [comment]
New bugs added to comment ^^^

**Comment by lwestrom** [comment]
New bugs and comments added to comment above ^^^

**Comment by OnyxSpartanII** [comment]
All known bugs resolved.
